export const ADD_GROUP = 'ADD_GROUP';
export const CHANGE_TODO_IS_COMPLETED_STATUS = 'CHANGE_TODO_IS_COMPLETED_STATUS';
export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const EDIT_TODO_GROUP_TITLE = 'EDIT_TODO_GROUP_TITLE';
export const DELETE_TODO_GROUP = 'DELETE_TODO_GROUP';
export const MOVE_TODO_GROUP_FORWARD = 'MOVE_TODO_GROUP_FORWARD';
